using System;

namespace Shared
{
    public class AppUser
    {
        /// <summary>
        /// The name of the user
        /// </summary>
        public string Username { get; set; }

        /// <summary>
        /// The Email serves as the Unique Key which maps to the RowKey in the AppUser Table Entity
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// This gets updated once the user confirms his or her email address
        /// </summary>
        public bool EmailConfirmed { get; set; }

        /// <summary>
        /// This corresponds to the InstanceId generated by the Azure Durable Function Orchestrator
        /// </summary>
        public string OrchestrationId { get; set; }

        /// <summary>
        /// This is a custom-generated code for each user
        /// It will be passed into the EmailConfirmation query
        /// in place of the OrchestrationId
        /// </summary>
        public string ReferenceCode { get; set; }

        public DateTime Created { get; set; }

        public DateTime Updated { get; set; }
    }
}